### ISSUE TITLE
Code for Experiments

### ISSUE THREAD

**Issue by tanchongmin** [JiuTian-VL/Optimus-1#1]
Great paper! Really enjoyed it and will be giving a presentation about it on my YouTube channel!

As a side note, would the code be provided online soon?

Also, would like to see if you'd like to present on it / answer questions on it as well on my YouTube channel. 

Please connect at: https://www.linkedin.com/in/john-chong-min-tan-94652288/

Great work once again!

**Comment by lizaijing** [comment]
Thank you for your attention to our work! We will release the codes as soon as possible after the paper is published.
We are pleased that you are willing to share our work on your YouTube channel.
If you have any questions, feel free to contact with us at lzj14011 [at] gmail.com

**Comment by lizaijing** [comment]
We have released the code, enjoy it!
