### ISSUE TITLE
Wrong import path in scripts/test_minerl.sh

### ISSUE THREAD

**Issue by RobotiX101** [JiuTian-VL/Optimus-1#2]
# Problem:
In `test_minerl.sh`:
```
python -m optimus1.tests.test_optimus1 minerl.port=9000 evaluate="[0]"
```
but `test_optimus1.py` locates at  `./src/optimus1/test_optimus1.py`. 

# Solution
So change the scripts to
```
python -m optimus1.test_optimus1 minerl.port=9000 evaluate="[0]"
```

**Comment by lizaijing** [comment]
Thank you for the correction. We have modified the script.

**Comment by liyichen-cly** [comment]
Hi, I encountered another problem.
![image](https://github.com/user-attachments/assets/66aeae1e-6eec-4947-8f80-b828b2a0dfc6)

**Comment by xieyuquanxx** [comment]
> Hi, I encountered another problem. ![image](https://private-user-images.githubusercontent.com/42406927/402803014-66aeae1e-6eec-4947-8f80-b828b2a0dfc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4MzcwMDEsIm5iZiI6MTczNjgzNjcwMSwicGF0aCI6Ii80MjQwNjkyNy80MDI4MDMwMTQtNjZhZWFlMWUtNmVlYy00OTQ3LThmODAtYjgyOGIyYTBkZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE0VDA2MzgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4OGRiMDE0YjJmMGIxZDFhODUyZWYwNGUyMjcyZmMwMzAzYTExMGQyNjg2ZWQ4YWRlMzFjOTA1OTNlMzc2MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qgm7vovbOPhaBaOOoOZQj5frPw5-yoX-oOohMAV6eYo)

Hi, changing `minerl.port` to `server.port` may be solved
