### ISSUE TITLE
Experiment scripts to reproduce the paper's table and figures. (Table 1, Figure 5-(b))

### ISSUE THREAD

**Issue by sjlee-me** [JiuTian-VL/Optimus-1#4]
Thank you for your great work!

Can you provide experiment scripts to reproduce the Table 1 and Figure 5-(b) in the paper?

I want to reproduce the paper's experiments, but it seems that this repository does not include the scripts.
I think the script should includes free exploration phase, teacher guidance phase, and then final evaluation phase.

**Comment by lizaijing** [comment]
Thank you for your suggestion. We have released the evaluation script, as well as a base Memory (Knowledge+Experience), so you can keep expanding Optimus-1's memory, and reproducing the results from the paper. As for how to start from scratch (free exploration phase and teacher guidance phase), that part of the script will be released later along with the visualization script.
